### ISSUE TITLE
Migrant issues

### ISSUE THREAD

**Issue by rosskevin** [code-and-effect/effective_addresses#13]
Migrant is causing issues with superclass.schema discovery.  Essentially, effective_addresses uses migrant, and we don't.  Since migrant isn't all that savvy on schema discovery, our inclusion of effective_addresses breaks with 

```ruby
undefined method `add_association' for nil:NilClass
/Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/migrant-1.5.0/lib/migrant/schema.rb:111:in `add_association'
/Users/kross/.rvm/gems/ruby-2.2.0@acme/gems/migrant-1.5.0/lib/migrant/model_extensions.rb:8:in `belongs_to'
```

This could be patched in migrant, or we could yank migrant from this project.  Question @matt-riemer, how much value is migrant providing here?  It appears not to have updates since 2013.

This guy attempted some similar updates, but it doesn't quite cover our case:
https://github.com/pnomolos/migrant/commit/f7969778d9d8591e518d3ebf79cc2ad28cea9647
https://github.com/pnomolos/migrant/commit/9b8723c683ba9836b94d8bf794bd171e882d5f61

The conditional would likely have to be something like `self.superclass.schema.presence`

**Comment by jfeaver** [comment]
Hi @rosskevin,

Thanks for trying out effective_addresses and letting us know about this issue you're having.  Effective addresses and other effective gems have been developed with migrant mostly as a personal preference rather than a necessity.  @matt-riemer is on vacation today but I think he would probably approve of a PR that removes the gem and I'll mention it to him in the next couple days.

**Comment by matt-riemer** [comment]
Yea, I really like migrant because it gives you the `structure do .. end` block so you can easily see what attributes are on your model without switching to the schema.rb file.  It auto generates database migrations for you, and gives you a nice validation DSL.

That being said, it probably doesn't belong in a gem that other apps would depend on.

I agree this should be removed from `effective_addresses`.

@rosskevin, @jfeaver   I have merged the two PRs (removing migrant, and adding geocoder support!) and pushed effective_addresses 1.3.0 to rubygems

Thanks!
